# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "ccf-terraform-backend"
    encrypt = true
    key     = "terraform-workspaces-terragrunt-ansible/non-prod/us-east-1/dev/terraform.tfstate"
    region  = "ap-southeast-2"
  }
}
